version: '3'

services:
  postgres:
    container_name: "ddd-postgres"
    build: ./postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=ddduser
      - POSTGRES_PASSWORD=passw0rd
    volumes:
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./postgres/volumes/postgresql:/var/lib/postgresql/data
    networks:
      - dddnet

networks:
  dddnet: